[theme]
# Primary accent color for interactive elements
primaryColor = "#667eea"

# Background color for the main content area
backgroundColor = "#0f0c29"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#1a1a2e"

# Color used for almost all text
textColor = "#ffffff"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Enable CORS protection
enableCORS = true

# Enable XSRF protection
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader
maxUploadSize = 200

[browser]
# Internet address where users should point their browsers to connect to the app
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false